### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [jcaesar/lls#1]
Could you please tag the source? This allows distributions to get the complete source from GitHub as tarball instead of working with commits which point to the different versions.

Thanks

**Comment by jcaesar** [comment]
[Done](https://github.com/jcaesar/lls/releases/tag/v0.1.0). And thank you for packaging it. (Though I just wondered whether [the source](https://crates.io/api/v1/crates/lls/0.1.0/download) couldn't be acquired from crates.io. That'd also be guaranteed to not change.)
